spring:
  application:
    name: KanbanSSam
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/KanbanSSam

jwt:
  secret:
    key: ${JWT_KEY}