spring:
  application:
    name: KanbanSSam
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: k1045314!
    username: root
    url: jdbc:mysql://localhost:3306/kanban

jwt:
  secret:
    key: ${JWT_KEY}